name: Pylint
on: [push]

jobs:
  lint:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      
      - name: Install dependencies
        run: |
          pip install pylint pywin32 wmi keyboard
          
      - name: Run Pylint
        run: |
          pylint --disable=missing-docstring,invalid-name,line-too-long,import-error GhostTyper.py
