name: Simplified Pylint
on: [push]

jobs:
  lint:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install deps
        run: pip install pylint pywin32
      - name: Check code
        run: pylint --disable=all --enable=E,F,C0103 GhostTyper.py
